python src/VPINN_train.py\
    --solver regular\
    --params D001N020K020\
    --tfs "Finite Elements"\
    --act tanh\
    --freq 8.\
    --epochs 5000\
    --lr 1e-03\
    --init ls\
    --dir "./results/tmp/"\
    --plot_grads True
